# single replica - no persistence
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
spec:
  selector:
    matchLabels:
      name: kitchen
  replicas: 1
  template:
    metadata:
      labels:
        name: kitchen
    spec:
      containers:
        - image: anthonyamanse/kitchenconsumer:1.0
          name: kitchen
          env:
            - name: MONGODB_REPLICA_HOSTNAMES
              value: 'mongo:27017'
          envFrom:
            - secretRef:
                name: kafka-credentials