# single replica - no persistence
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  selector:
    matchLabels:
      name: orders
  replicas: 1
  template:
    metadata:
      labels:
        name: orders
    spec:
      containers:
        - image: anthonyamanse/orderconsumer:1.0
          name: orders
          env:
            - name: MONGODB_REPLICA_HOSTNAMES
              value: 'mongo:27017'
          envFrom:
            - secretRef:
                name: kafka-credentials