apiVersion: v1
kind: Route
metadata:
  name: apiservice-path-creatorder
spec:
  host: HOSTNAME
  path: "/createOrder"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apiservice
---
apiVersion: v1
kind: Route
metadata:
  name: apiservice-path-status
spec:
  host: HOSTNAME
  path: "/status"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apiservice
---
apiVersion: v1
kind: Route
metadata:
  name: apiservice-path-restaurants
spec:
  host: HOSTNAME
  path: "/restaurants"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apiservice
---
apiVersion: v1
kind: Route
metadata:
  name: apiservice-path-user
spec:
  host: HOSTNAME
  path: "/user"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: apiservice
---
apiVersion: v1
kind: Route
metadata:
  name: realtimedata-path-events
spec:
  host: HOSTNAME
  path: "/events"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: realtimedata
---
apiVersion: v1
kind: Route
metadata:
  name: podconsumerdata-path-consumers
spec:
  host: HOSTNAME
  path: "/consumers"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: podconsumerdata
---